Upgrade to latest ssh-credentials to fix NoSuchMethodError thanks to binary-incompatible change in ssh-credentials
SEVERE: Failed to sync slave
 java.lang.NoSuchMethodError: hudson.plugins.sshslaves.SSHLauncher.getCredentials()Lcom/cloudbees/jenkins/plugins/sshcredentials/SSHUser;
       at com.cloudbees.jenkins.plugins.mtslavescloud.MansionRetentionStrategy$1.run(MansionRetentionStrategy.java:63)
       at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
       at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
       at java.util.concurrent.FutureTask.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at java.lang.Thread.run(Unknown Source)